# sudo apt-get update && sudo apt-get install samba smbclient cifs-utils -y
# vi /etc/samba/smb.conf
# sudo mkdir /share
# sudo chmod 777 /share
# sudo chown -R Administrator /share
# sudo smbpasswd -a Administrator
# sudo systemctl start smbd
# sudo systemctl enable smbd
# sudo systemctl restart smbd

[global]
   workgroup = WORKGROUP
   netbios name = xtd
   server string = xtd
   log file = /var/log/samba/log.%m
   max log size = 50
   security = user
   map to guest = Bad User

[share]
    comment = some comments
    path = /share
    writable  = yes
    browseable = yes
    read only = no
    guest ok  = yes
