# /etc/samba/smb.conf
# sudo systemctl restart smb && sudo systemctl status smb
# smbd.service - Samba SMB Daemon
#     Loaded: loaded (/lib/systemd/system/smbd.service; enabled; preset: enabled)
#     Active: active (running) since Mon 2024-03-04 09:46:08 UTC; 1min 5s ago
#       Docs: man:smbd(8)
#             man:samba(7)
#             man:smb.conf(5)
#    Process: 4680 ExecCondition=/usr/share/samba/is-configured smb (code=exited>
#    Process: 4682 ExecStartPre=/usr/share/samba/update-apparmor-samba-profile (>
#   Main PID: 4691 (smbd)
#     Status: "smbd: ready to serve connections..."
#      Tasks: 4 (limit: 2108)
#     Memory: 9.3M
#        CPU: 109ms
#     CGroup: /system.slice/smbd.service
#             ├─4691 /usr/sbin/smbd --foreground --no-process-group
#             ├─4693 "smbd: notifyd" .
#             ├─4694 "smbd: cleanupd "
#             └─4696 "smbd: client [10.211.55.2]"

[global]
   workgroup = WORKGROUP
   netbios name = xtd
   server string = xtd
   log file = /var/log/samba/log.%m
   max log size = 50
   security = user
   map to guest = Bad User

[share]
    comment = some comments
    path = /share
    writable  = yes
    browseable = yes
    read only = no
    guest ok  = yes
